### ISSUE TITLE
[DISCUSSION] Thank you! 

### ISSUE THREAD

**Issue by angelhdzmultimedia** [piscis/nuxt3-nestjs-boilerplate#77]
I was thinking about doing this, but instead of trying it your way, because I still didn't know about the `toNodeMiddleware` hook to convert Node middleware to h3 (or nitro?), I went crazy and just made my own Nest-alike TypeScript decorators on top of `defineEventHandler` hook. It was decent, but not what I really wanted.

Today I was reading the Nuxt sponsors and saw you, and decided to check if you had anything new besides the Quasar boilerplate, and saw this boilerplate and was shocked!

So I tried it and ohhh man! So brutal! Love it!

Also added `chokidar` package to watch for changes in the schema.prisma to call `pnpx prisma generate` automatically.

I am sooo going to have fun with this beautiful fusion between Nuxt and Nest this week!!! 🔥🤯☕😍🤝🎉

Thank you so much! Wishing you health, peace, and success!

P.S: By the way, did you get to check the `nuxt-quasar-ui` module?

**Comment by piscis** [comment]
@angelhdzmultimedia hey thank you for your feedback :-)  I hope it helps! I think `fromNodeMiddleware` is just the right tool when you have a middleware that is normally compatible with expressJS middleware callback style and you want to hook it up with the h3 part of nuxt 3 

Regarding `nuxt-quasar-ui` module I must say I basically stopped using quasar for new projects because of their resistance to consider nuxt over their own ssr solution and I'm afraid spending their time to ship their own SSR will hurt the project in  the long run ... Anyway .. In my current project I use the following stack  `Nuxt3` / `PrimeVue` / `TailwindCSS` / `Prisma` / `TRPC` / `Supabase` where `PrimeVue` / `TailwindCSS` took the place of `quasar`. Although I must say I'm currently looking at `UnoCSS` to get additional functionality like `Iconify` and so on buttttt ... that's another story. ...

Have a good one!
